Repository WildCodeSchool-2024-09/JS-RemoteFR-Vendangeurs-P2-JAM-Devs, pull requests merged in 2024-11, with the labels that each got.

#49 [feat] install TailwindCSS and setup
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.tsx
  client/src/assets/fonts/jokcey-one/JockeyOne-Regular.ttf
  client/src/assets/fonts/roboto/Roboto-Bold.ttf
  client/src/assets/fonts/roboto/Roboto-Medium.ttf
  client/src/assets/fonts/roboto/Roboto-Regular.ttf
  client/src/assets/images/background.webp
  client/tailwind.config.js
  package-lock.json
Labels: REVIEWD

#50 [Feat] create banner and home page
  client/src/assets/icons/album.jpg
  client/src/assets/icons/album2.jpg
  client/src/assets/icons/album_face.webp
  client/src/assets/icons/heart.svg
  client/src/assets/icons/jimin.webp
  client/src/assets/icons/play.svg
  client/src/assets/icons/riri.png
  client/src/assets/icons/tayc.jpeg
  client/src/assets/icons/who.jpeg
  client/src/components/Banner.tsx
  client/src/pages/Home.tsx
Labels: REVIEWD

#51 [FEAT] create navbar component and routing
  client/src/App.tsx
  client/src/assets/icons/Home.svg
  client/src/assets/icons/Infos.svg
  client/src/assets/icons/LogoJamOrange.svg
  client/src/assets/icons/Search.svg
  client/src/components/Navbar.tsx
  client/src/main.tsx
Labels: CHANGE_REQUESTED, CORRECTIONS_DONE, REVIEWD

#64 [Feat] adding a new page for display tracks of playlist
  client/src/assets/.gitkeep
  client/src/components/.gitkeep
  client/src/components/BannerHome.tsx
  client/src/components/BannerPlaylist.tsx
  client/src/components/BannerSection.tsx
  client/src/components/Playlists.tsx
  client/src/components/Wrapper.tsx
  client/src/main.tsx
  client/src/pages/.gitkeep
  client/src/pages/Home.tsx
  client/src/pages/PlaylistPage.tsx
  client/src/services/.gitkeep
  client/src/services/formatDuration.ts
  client/src/types/type.ts
  client/tailwind.config.js
  client/vite.config.ts
Labels: REVIEWD

#65 [feat]added buttons for playing music
  README.md
  client/src/App.tsx
  client/src/assets/Icons/Play.svg
  client/src/assets/icons/play.svg
  client/src/assets/picture/Pochette.jpg
  client/src/components/PlayButton.tsx
  client/src/components/Player.tsx
  client/src/components/Playlists.tsx
  client/src/context/PlayerContext.tsx
  client/src/types/type.ts
Labels: REVIEWD

#66 [feat] create routes and pages to navigate between albums and tracks
  client/src/App.css
  client/src/assets/Icons/Play.svg
  client/src/components/AlbumsList.tsx
  client/src/components/Artists.tsx
  client/src/components/BannerSection.tsx
  client/src/components/HeroBanner.tsx
  client/src/components/Navbar.tsx
  client/src/components/PlayButton.tsx
  client/src/components/Player.tsx
  client/src/components/Playlists.tsx
  client/src/components/TopAlbum.tsx
  client/src/components/TrackList.tsx
  client/src/components/Wrapper.tsx
  client/src/main.tsx
  client/src/pages/AlbumDetails.tsx
  client/src/pages/ArtistPage.tsx
  client/src/pages/Home.tsx
  client/src/pages/PlaylistPage.tsx
  client/src/services/.gitkeep
  client/src/types/type.ts
  client/src/utils/formatDate.ts
  client/src/utils/formatDuration.ts
  client/src/utils/formatNb.ts
  client/vite.config.ts
Labels: CONFLICTS_RESOLVED, CORRECTIONS_DONE, REVIEWD

#82 [feat] added navigation buttons
  client/src/App.tsx
  client/src/assets/Icons/NextPage.svg
  client/src/assets/Icons/PreviousPage.svg
  client/src/assets/icons/Home.svg
  client/src/components/Artists.tsx
  client/src/components/BannerHome.tsx
  client/src/components/Navbar.tsx
  client/src/components/NavigationButtons.tsx
  client/src/components/Playlists.tsx
  client/src/components/ScrollToTop.tsx
  client/src/components/TrackList.tsx
  client/src/pages/ArtistPage.tsx
Labels: REVIEWD

#83 [Feat] Added the functional search bar
  client/src/assets/Icons/cross.svg
  client/src/components/Navbar.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchContainer.tsx
  client/src/components/SearchResults.tsx
  client/src/types/type.ts
  client/src/utils/truncateText.ts
  package-lock.json
Labels: REVIEWD

#85 [feat] Add session storage and centralize api calls
  client/index.html
  client/src/assets/Icons/BreackDisc.svg
  client/src/assets/icons/album_face.webp
  client/src/components/Artists.tsx
  client/src/components/BannerHome.tsx
  client/src/components/BannerPlaylist.tsx
  client/src/components/HeroBanner.tsx
  client/src/components/Loader.tsx
  client/src/components/Navbar.tsx
  client/src/components/Playlists.tsx
  client/src/components/TrackList.tsx
  client/src/main.tsx
  client/src/pages/AlbumDetails.tsx
  client/src/pages/ArtistPage.tsx
  client/src/pages/Error404.tsx
  client/src/pages/Home.tsx
  client/src/pages/PlaylistPage.tsx
  client/src/services/.gitkeep
  client/src/services/deezerApi.ts
  client/src/utils/getRandomIds.ts
  client/src/utils/shuffleArray.ts
Labels: REVIEWD

#89 [feat] modifying the latest api routes
  client/src/components/PlayButton.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchResults.tsx
  client/src/pages/AlbumDetails.tsx
  client/src/services/deezerApi.ts
Labels: REVIEWD

#91 Delete client/src/assets/Icons directory
  client/src/assets/Icons/BreackDisc.svg
  client/src/assets/Icons/Like.svg
  client/src/assets/Icons/Mute.svg
  client/src/assets/Icons/Next.svg
  client/src/assets/Icons/NextPage.svg
  client/src/assets/Icons/Pause.svg
  client/src/assets/Icons/Play.svg
  client/src/assets/Icons/Previous.svg
  client/src/assets/Icons/PreviousPage.svg
  client/src/assets/Icons/Random.svg
  client/src/assets/Icons/RandomActif.svg
  client/src/assets/Icons/RedLike.svg
  client/src/assets/Icons/Repeat.svg
  client/src/assets/Icons/RepeatActif.svg
  client/src/assets/Icons/Speaker.svg
  client/src/assets/Icons/cross.svg
Labels: REVIEWD

#94 [fix] fix_icons_folder_3
  client/public/vite.svg
  client/src/assets/icons/Home.svg
  client/src/assets/icons/Infos.svg
  client/src/assets/icons/Like.svg
  client/src/assets/icons/LogoJamOrange.svg
  client/src/assets/icons/Mute.svg
  client/src/assets/icons/Next.svg
  client/src/assets/icons/NextPage.svg
  client/src/assets/icons/Pause.svg
  client/src/assets/icons/Play.svg
  client/src/assets/icons/Previous.svg
  client/src/assets/icons/PreviousPage.svg
  client/src/assets/icons/Random.svg
  client/src/assets/icons/RandomActif.svg
  client/src/assets/icons/RedLike.svg
  client/src/assets/icons/Repeat.svg
  client/src/assets/icons/RepeatActif.svg
  client/src/assets/icons/Search.svg
  client/src/assets/icons/Speaker.svg
  client/src/assets/icons/cross.svg
  client/src/assets/images/BreakDisc.svg
  client/src/pages/Error404.tsx
Labels: REVIEWD

#96 [fix] proxy replacement for api url then deploy
  client/src/services/deezerApi.ts
Labels: REVIEWD

#98 [fix]solving a deployment issue
  client/src/components/Navbar.tsx
  client/src/components/SearchBar.tsx
  client/src/components/SearchResults.tsx
  client/src/pages/ArtistPage.tsx
  client/src/services/deezerApi.ts
Labels: REVIEWD
